### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by LeeYang2019** [cortezjl/MyWorkWeek#2]
# Design/Code Review 1

### Reviewer:Lee Yang

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| Great idea. Very practical and can be used right away. Great job walking us through your problem statement and how you plan to solve it. I like the idea of using a calendar API to display the dates of holidays, etc.|
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | Great use of flowcharts to walk us through your project. A thought though as I was reflecting on your presentation. One thing I wasn't sure on is: if I'm a user and requesting time off for a particular day, do I also see who else has requested time off for that day too? I would imagine that once the admin/manager approves the time off, if he or she does for one or more individuals, that I would.|
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| We didn't get that in depth with the actual code review, as we were running out of time, but Julie did show us the different classes she had written up, as well as the DAOs for each of those classes. Everything seems in order.|
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverages. | We didn't do much code review but having glossed over your code afterwards, it seems you did a great job writing them. Its clean and easy to follow. |

**Comment by pawaitemadisoncollege** [comment]
@LeeYang2019 Looks like some System.out.println statements in there....  I encourage you guys to review the project outside of the in-person code review too - it's hard to be thorough in the short time you reviewed in-person.
